### ISSUE TITLE
Levels and Wall Height compatibility

### ISSUE THREAD

**Issue by Dialectikal** [WesBelmont/token-lean#9]
Hello. I've been using this module for awhile now and I love it. However, I recently noticed that there is a conflict on some of my maps with Levels, Wall Height, and this module. Now my players can select tokens that are in Fog of War. Is this something that can be managed? I would hate to have to take this option away from my players.

I am on the latest version of each module and Foundry, and used Find the Culprit to narrow it down to just those three modules.

**Comment by WesBelmont** [comment]
Levels and wall height had a big update recently. I've been busy with uni but I have some time to fix it this week. I'll try to get a fix out tonight.

**Comment by Dialectikal** [comment]
If you can manage it this week that would be fantastic. Thanks!

**Comment by WesBelmont** [comment]
I've released a new version with the fix. It should be good to go again.

**Comment by Dialectikal** [comment]
I'm still seeing the effect with the latest version:
![image](https://user-images.githubusercontent.com/31572084/164879454-a0bc3aaf-680c-46a1-8c3d-e8cb02f995e7.png)

Do I need to update or replace something?

**Comment by WesBelmont** [comment]
Not sure. Token Lean version 1.1.3 is working in my tests. I assume the bar on the right is from a token that is visible to the players? If you enable the debug feature in levels, it may assist in finding out which walls are blocking vision correctly.

**Comment by Dialectikal** [comment]
Ok, so it looks like it has been resolved for most cases. The issue only seems to occur when vision is removed from a player's primary token, or when their token is made invisible:
![image](https://user-images.githubusercontent.com/31572084/164885071-59eaf288-0600-4ac1-88f3-f4ff3c4de6fb.png)

This is probably why you aren't seeing it in your tests. Most of the time, my players won't be able to see the other tokens. But a lot of people use the invisibility functionality to move players around between areas or to signify being blinded or in darkness. In my case, I was using it to record sessions and to test player functionality. That's why it showed up in my previous screenshot, even though there was still vision.

The walls are standard, with the maximum range set for Wall Height. The map itself has been in use for a few months without any change to the walls.

Not sure if that helps or not. Please let me know if you want me to check anything else.
